version: "3.4"
services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - ./redisdata:/data
  db:
    image: elestio/postgres:16
    restart: unless-stopped
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=paperless
      - POSTGRES_USER=paperless
      - POSTGRES_PASSWORD=paperless
  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:${SOFTWARE_VERSION_TAG}
    restart: unless-stopped
    depends_on:
      - db
      - broker
      - gotenberg
      - tika 
    ports:
      - "172.17.0.1:8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://172.17.0.1:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./data:/usr/src/paperless/data
      - ./media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - ./consume:/usr/src/paperless/consume
    env_file: .env
    environment:
      - PAPERLESS_REDIS=redis://broker:6379
      - PAPERLESS_DBHOST=db
      - PAPERLESS_ADMIN_USER=${ADMIN_EMAIL}
      - PAPERLESS_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - PAPERLESS_URL=${PAPERLESS_URL}
      - PAPERLESS_TIKA_ENABLED=1
      - PAPERLESS_TIKA_GOTENBERG_ENDPOINT=http://gotenberg:3000
      - PAPERLESS_TIKA_ENDPOINT=http://tika:9998
  gotenberg:
    image: elestio/gotenberg
    restart: always
    ports:
      - 172.17.0.1:3000:3000
  tika:
    user: 0:0
    stdin_open: true
    tty: true
    image: apache/tika
    restart: always
    ports:
      - "172.17.0.1:9998:9998"
    volumes:
      - ./storage:/var
